fix(paging): fix the AttributeError caused by "StructScalarWrapper"
Error Message:
AttributeError: 'StructScalarWrapper' object has no attribute 'as_py'

PR Closed: https://github.com/Graviti-AI/graviti-python-sdk/pull/515